server:
  port: 8088

spring:
  profiles:
    active: local
  application:
    name: overpass-service-bridge

  datasource:
#    data: classpath:db/data.sql
#    platform: h2
#    schema: classpath:db/schema.sql
#    url: jdbc:h2:~/test    # 持久化到 文件     # 再次启动时，初始化的sql不会再执行，并且操作后新增减的数据状态将一直保存
    url: jdbc:h2:mem:dbtest # 持久化到 数据库   # 每次启动时，数据都会重新初始化
    driverClassName: org.h2.Driver
    username: root
    password: root
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

#  datasource:
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:file:D:/h2Data/test;AUTO_SERVER=TRUE
#    username: sa
#    password:
#  jpa:
#    show-sql: true
#    hibernate:
#      # 每次运行程序，没有表格会新建表格，表内有数据不会清空，只会更新
#      ddl-auto: update




#mybatis:
#  type-aliases-package: com.nexneo.web.pojo.model
#  mapper-locations: classpath:mapper/*.xml
#  configuration:
#    map-underscore-to-camel-case: true
#    log-impl: org.apache.ibatis.logging.log4j2.Log4j2Impl
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl



#logging:
#  config: classpath:log4j2_${spring.profiles.active}.yml
#  level:
#    com.nexneo.*: debug
#    com.nexneo.web.mapper: debug
#    # 去除无关异常打印 >>>>>>>>>>> xxl-job provider netty_http server caught exception
#    com.xxl.job.core.server.EmbedServer: OFF

## 商品信息批量新增的数量
#nexneo-web-insertGoodsBatchNum: 500
## 商品信息-允许更新的开关
#nexneo-web-goodsInfoAllowUpdateClose: true
## 用户信息批量新增的数量
#nexneo-web-insertUserBatchNum: 500
## 用户信息-允许更新的开关
#nexneo-web-userInfoAllowUpdateClose: true